import { MenuItem } from "@/types/types";

export const leftMenuItems: MenuItem[] = [
  {
    id: "dashboard",
    icon: "NiHome",
    label: "Dashboard",
    description: "Main dashboard",
    color: "text-primary",
    href: "/dashboard",
    roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
  },
  {
    id: "curriculum",
    icon: "NiBook",
    label: "Curriculum",
    description: "Curriculum management",
    color: "text-primary",
    href: "/dashboard/curriculum",
    roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
    children: [
      {
        id: "subjects",
        icon: "NiBook",
        label: "Mata Pelajaran",
        href: "/dashboard/curriculum/subjects",
        description: "Subject Management",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "phases",
        icon: "NiBook",
        label: "Fase",
        href: "/dashboard/curriculum/phases",
        description: "Phase Management",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "elements",
        icon: "NiBook",
        label: "Elemen",
        href: "/dashboard/curriculum/elements",
        description: "Element Management",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "subelements",
        icon: "NiBook",
        label: "Subelemen",
        href: "/dashboard/curriculum/subelements",
        description: "Subelement Management",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "academic-foundation",
        icon: "NiBook",
        label: "Academic Foundation",
        description: "Academic Foundation Management",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
        children: [
          {
            id: "subject-categories",
            icon: "NiBook",
            label: "Kategori Mata Pelajaran",
            href: "/dashboard/academic-foundation/subject-categories",
            description: "Subject Category Management",
            roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
          },
          {
            id: "academic-years",
            icon: "NiCalendar",
            label: "Tahun Ajaran",
            href: "/dashboard/academic-foundation/academic-years",
            description: "Academic Year Management",
            roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
          },
          {
            id: "semesters",
            icon: "NiFolder",
            label: "Semester",
            href: "/dashboard/academic-foundation/semesters",
            description: "Semester Management",
            roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
          },
        ],
      },
      {
        id: "cp",
        icon: "NiDocumentFull",
        label: "CP",
        href: "/dashboard/cp",
        description: "Curriculum Plan",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "tp",
        icon: "NiDocumentFull",
        label: "TP",
        href: "/dashboard/tp",
        description: "Teaching Plan",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "atp",
        icon: "NiDocumentFull",
        label: "ATP",
        href: "/dashboard/atp",
        description: "Annual Teaching Plan",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
    ],
  },
  {
    id: "learning-design",
    icon: "NiGraduation",
    label: "Learning Design",
    description: "Learning design and materials",
    color: "text-primary",
    roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
    children: [
      {
        id: "modul-ajar",
        icon: "NiBook",
        label: "Modul Ajar",
        href: "/dashboard/modul-ajar",
        description: "Teaching modules",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
    ],
  },
  {
    id: "assessment",
    icon: "NiListCheck",
    label: "Assessment",
    description: "Assessment management",
    color: "text-primary",
    href: "/dashboard/assessment",
    roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
    children: [
      {
        id: "assessment-list",
        icon: "NiListCheck",
        label: "Assessment",
        href: "/dashboard/assessment",
        description: "Assessment list",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "rubric",
        icon: "NiStars",
        label: "Rubric",
        href: "/dashboard/rubric",
        description: "Assessment rubrics",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
      {
        id: "narrative-report",
        icon: "NiDocumentFull",
        label: "Narrative Report",
        href: "/dashboard/narrative-reports",
        description: "Narrative reports",
        roles: ["TEACHER", "SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
    ],
  },
  {
    id: "workflow",
    icon: "NiPath",
    label: "Workflow",
    description: "Workflow and approvals",
    color: "text-primary",
    roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
    children: [
      {
        id: "approval-queue",
        icon: "NiCheckSquare",
        label: "Approval Queue",
        href: "/dashboard/workflow",
        description: "Pending approvals",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
    ],
  },
];

export const leftMenuBottomItems: MenuItem[] = [
  {
    id: "administration",
    icon: "NiSettings",
    label: "Administration",
    href: "/dashboard/settings",
    color: "text-primary",
    roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
    children: [
      {
        id: "settings",
        icon: "NiSettings",
        label: "Settings",
        href: "/dashboard/settings",
        description: "System settings",
        roles: ["SYSTEM_ADMIN", "SCHOOL_ADMIN"],
      },
    ],
  },
];
