import { MenuItem } from "@/types/types";

export const leftMenuItems: MenuItem[] = [
  {
    id: "dashboard",
    icon: "NiHome",
    label: "Dashboard",
    description: "Main dashboard",
    color: "text-primary",
    href: "/dashboard",
    roles: ["teacher", "admin", "principal"],
  },
  {
    id: "curriculum",
    icon: "NiBook",
    label: "Curriculum",
    description: "Curriculum management",
    color: "text-primary",
    href: "/curriculum",
    roles: ["teacher", "admin", "principal"],
    children: [
      {
        id: "cp",
        icon: "NiDocumentFull",
        label: "CP",
        href: "/cp",
        description: "Curriculum Plan",
        roles: ["teacher", "admin", "principal"],
      },
      {
        id: "tp",
        icon: "NiDocumentFull",
        label: "TP",
        href: "/tp",
        description: "Teaching Plan",
        roles: ["teacher", "admin", "principal"],
      },
      {
        id: "atp",
        icon: "NiDocumentFull",
        label: "ATP",
        href: "/atp",
        description: "Annual Teaching Plan",
        roles: ["teacher", "admin", "principal"],
      },
    ],
  },
  {
    id: "learning-design",
    icon: "NiGraduation",
    label: "Learning Design",
    description: "Learning design and materials",
    color: "text-primary",
    href: "/learning-design",
    roles: ["teacher", "admin", "principal"],
    children: [
      {
        id: "modul-ajar",
        icon: "NiBook",
        label: "Modul Ajar",
        href: "/modul-ajar",
        description: "Teaching modules",
        roles: ["teacher", "admin", "principal"],
      },
    ],
  },
  {
    id: "assessment",
    icon: "NiListCheck",
    label: "Assessment",
    description: "Assessment management",
    color: "text-primary",
    href: "/assessment",
    roles: ["teacher", "admin", "principal"],
    children: [
      {
        id: "assessment-list",
        icon: "NiListCheck",
        label: "Assessment",
        href: "/assessment",
        description: "Assessment list",
        roles: ["teacher", "admin", "principal"],
      },
      {
        id: "rubric",
        icon: "NiStars",
        label: "Rubric",
        href: "/rubric",
        description: "Assessment rubrics",
        roles: ["teacher", "admin", "principal"],
      },
      {
        id: "narrative-report",
        icon: "NiDocumentFull",
        label: "Narrative Report",
        href: "/narrative-report",
        description: "Narrative reports",
        roles: ["teacher", "admin", "principal"],
      },
    ],
  },
  {
    id: "workflow",
    icon: "NiPath",
    label: "Workflow",
    description: "Workflow and approvals",
    color: "text-primary",
    href: "/workflow",
    roles: ["admin", "principal"],
    children: [
      {
        id: "approval-queue",
        icon: "NiCheckSquare",
        label: "Approval Queue",
        href: "/workflow",
        description: "Pending approvals",
        roles: ["admin", "principal"],
      },
    ],
  },
];

export const leftMenuBottomItems: MenuItem[] = [
  {
    id: "administration",
    icon: "NiSettings",
    label: "Administration",
    href: "/settings",
    color: "text-primary",
    roles: ["admin"],
    children: [
      {
        id: "settings",
        icon: "NiSettings",
        label: "Settings",
        href: "/settings",
        description: "System settings",
        roles: ["admin"],
      },
    ],
  },
];
